### ISSUE TITLE
Update dependencies and make a new release

### ISSUE THREAD

**Issue by nwalfield** [kinnison/enumber#4]
It's been a few years since the last release.  Although I don't need any new features, I'd appreciate a new release with updated dependencies.

@kinnison, if you don't have time, I'll try and get to that this week.

**Comment by kinnison** [comment]
Hi Neil.  Do you mean a shift to syn 2 ?  If so it should be relatively simple to do most of that for me.  If I don't find time before say tomorrow evening, feel free to sort a PR out.

**Comment by nwalfield** [comment]
Yup, I meant moving to syn 2.  (I actually thought there was a second dependency, but I just checked again, and this is the only one that is out of date.)  I'd be grateful if you worked on this, thanks. :bow:

**Comment by kinnison** [comment]
Since internally no behaviour should have changed, I have released 0.3.1 using syn 2.  I hope that works for you; please let me know if anything breaks.

**Comment by nwalfield** [comment]
Thank a lot, Daniel!

**Comment by nwalfield** [comment]
By the way, I've tested it, and it works (at least, I haven't noticed any regressions :)).  Thanks again!
